
homepage:
    path: /
    controller: App\Controller\HomeController::index
    
app_contact:
    path: /contact
    controller: App\Controller\HomeController::contact

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register