homepage:
    path: /
    controller: App\Controller\HomeController::index
    
contact:
    path: /contact
    controller: App\Controller\HomeController::contact

avis:
    path: /avis
    controller: App\Controller\HomeController::avis

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register