controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: App\Controller\HomeController::index
    
contact:
    path: /
    controller: App\Controller\HomeController::contact

avis:
    path: /
    controller: App\Controller\HomeController::avis

horaires:
    path: /
    controller: App\Controller\HomeController::horaires
app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register